### PR TITLE
Feature/sync 3.5.2 with develop

### PR DESCRIPTION
**Pull request by msmcconnell**
# PR Details
## Description
Merge PR to formalize release of master into develop as part of CARMA release process for 3.5.0. 

Merge conflicts were fixed in inlane-cruising and the route node. 
## Motivation and Context

This PR brings the tested and reviewed contents of the master release/candidate into develop for final release preparation

## How Has This Been Tested?

This release branch (minus final version number changes) has been tested through the CARMA verification test plan.

## Checklist:
- [X] I have added any new packages to the sonar-scanner.properties file
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kjrush** [comment]
I think we may have a merge issue to debug based on this result from CI:

```
/opt/carma/src/CARMAPlatform/route/src/route_generator_worker.cpp: In member function 'lanelet::Optional<lanelet::routing::Route> route::RouteGeneratorWorker::reroute_after_route_invalidation(std::vector<Eigen::Matrix<double, 2, 1, 2> >&) const':
/opt/carma/src/CARMAPlatform/route/src/route_generator_worker.cpp:507:36: error: passing 'const std::vector<Eigen::Matrix<double, 2, 1, 2> >' as 'this' argument discards qualifiers [-fpermissive]
         destination_points_in_map_ = destination_points_in_map_temp; // Update our route point list
```

route_generator_worker.cpp:507 is in one of the change sets from Vanden Plas (inside this PR), so we may have a logical conflict between the develop branch contents somewhere and the code from master.

**Review by kjrush — APPROVED** [review]
